<a href="https://colab.research.google.com/github/roshnik1610/machine-learning-projects/blob/main/Flight_Booking_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df= pd.read_csv('/content/Flight_Booking.csv')

In [3]:
df

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1.0,5953.0
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1.0,5953.0
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1.0,5956.0
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1.0,5955.0
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1.0,5955.0
...,...,...,...,...,...,...,...,...,...,...,...,...
179741,179741,AirAsia,I5-974,Hyderabad,Night,one,Morning,Chennai,Economy,10.33,41.0,1776.0
179742,179742,AirAsia,I5-1518,Hyderabad,Evening,one,Morning,Chennai,Economy,12.75,41.0,1776.0
179743,179743,Indigo,6E-668,Hyderabad,Evening,zero,Evening,Chennai,Economy,1.25,41.0,1788.0
179744,179744,Indigo,6E-438,Hyderabad,Evening,zero,Night,Chennai,Economy,1.25,41.0,1788.0
179745,179745,Indigo,6E-6216,Hyderabad,Night,zero,Night,Che,NaN,NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179746 entries, 0 to 179745
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        179746 non-null  int64
 1   airline           179746 non-null  object
 2   flight            179746 non-null  object
 3   source_city       179746 non-null  object
 4   departure_time    179746 non-null  object
 5   stops             179746 non-null  object
 6   arrival_time      179746 non-null  object
 7   destination_city  179746 non-null  object
 8   class             179745 non-null  object
 9   duration          179745 non-null  float64
 10  days_left         179745 non-null  float64
 11  price             179745 non-null  float64
dtypes: float64(3), int64(1), object(8)
memory usage: 16.5+ MB

In [6]:
df.isnull().sum()

Unnamed: 0          0
airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               1
duration            1
days_left           1
price               1
dtype: int64

In [34]:
df.drop('Unnamed: 0', axis=1,inplace=True)

In [36]:
df = df.ffill()

In [37]:
df = df.bfill()

In [38]:
df

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,4,1273,1,2,2,5,6,0,2.17,1.0,5953.0
1,4,1252,1,1,2,4,6,0,2.33,1.0,5953.0
2,0,1096,1,1,2,1,6,0,2.17,1.0,5956.0
3,5,1416,1,4,2,0,6,0,2.25,1.0,5955.0
4,5,1406,1,4,2,4,6,0,2.33,1.0,5955.0
...,...,...,...,...,...,...,...,...,...,...,...
179741,0,1120,2,5,0,4,2,0,10.33,41.0,1776.0
179742,0,1024,2,2,0,4,2,0,12.75,41.0,1776.0
179743,3,455,2,2,2,2,2,0,1.25,41.0,1788.0
179744,3,209,2,2,2,5,2,0,1.25,41.0,1788.0
179745,3,384,2,5,2,5,1,0,1.25,41.0,1788.0

In [39]:
from sklearn.preprocessing import LabelEncoder

In [40]:
le= LabelEncoder()
for col in df.columns:
  if df[col].dtype=='object':
    df[col]=le.fit_transform(df[col])

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179746 entries, 0 to 179745
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   airline           179746 non-null  int64
 1   flight            179746 non-null  int64
 2   source_city       179746 non-null  int64
 3   departure_time    179746 non-null  int64
 4   stops             179746 non-null  int64
 5   arrival_time      179746 non-null  int64
 6   destination_city  179746 non-null  int64
 7   class             179746 non-null  int64
 8   duration          179746 non-null  float64
 9   days_left         179746 non-null  float64
 10  price             179746 non-null  float64
dtypes: float64(3), int64(8)
memory usage: 15.1 MB

In [42]:
y= df['price']
x= df.drop('price',axis=1)

In [43]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
import pandas as pd

def calculate_vif(x):
    vif = pd.DataFrame()
    vif["Feature"] = x.columns
    vif["VIF"] = [variance_inflation_factor(x.values, i)
                  for i in range(x.shape[1])]
    return vif

print(calculate_vif(x))

/usr/local/lib/python3.12/dist-packages/statsmodels/regression/linear_model.py:1784: RuntimeWarning: invalid value encountered in scalar divide
  return 1 - self.ssr/self.uncentered_tss

            Feature       VIF
0           airline  4.841136
1            flight  8.549157
2       source_city  2.677841
3    departure_time  2.679139
4             stops  1.435843
5      arrival_time  3.663571
6  destination_city  3.254473
7             class       NaN
8          duration  4.397945
9         days_left  3.866151

In [44]:

from sklearn.model_selection import train_test_split

In [85]:
x_train,x_test, y_train, y_test= train_test_split(x,y,train_size=0.8, random_state=7)

In [86]:
from sklearn.linear_model import LinearRegression

In [87]:
le= LinearRegression()

In [88]:

le.fit(x_train,y_train)

LinearRegression()

In [89]:






y_pred= le.predict(x_test)

In [90]:
from sklearn.metrics import r2_score

In [91]:
from sklearn.metrics import mean_squared_error

In [92]:
rmse= np.sqrt(mean_squared_error(y_test,y_pred))
r2 = r2_score(y_test,y_pred)
r2

0.41201753707098376

In [59]:

from sklearn.ensemble import RandomForestRegressor

In [61]:
x_train, x_test, y_train, y_test= train_test_split(x,y,train_size=0.8, random_state=1)

In [63]:
rf= RandomForestRegressor(n_estimators=100, random_state=42)

In [64]:
rf.fit(x_train, y_train)

RandomForestRegressor(random_state=42)

In [66]:
y_pred= rf.predict(x_test)

In [67]:
r2= r2_score( y_test,y_pred)

In [68]:
r2

0.8888217043397808